import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'

import { addCatalogue, fetchCatalogue, fetchCatalogues } from './catalogueAPI'
import { CatalogueDto } from './catalogueDtos'
import { ThunkStatus } from '../ThunkStatus'

export interface CatalogueState {
  catalogues: CatalogueDto[]
  catalogue?: CatalogueDto
  status: ThunkStatus
  error?: string
}

const initialState: CatalogueState = {
  catalogues: [],
  status: ThunkStatus.Idle,
}

export const fetchCataloguesAsync = createAsyncThunk(
  'catalogue/fetch',
  async () => {
    const response = await fetchCatalogues()
    // The value we return becomes the `fulfilled` action payload
    return response
  }
)

export const fetchCatalogueAsync = createAsyncThunk(
  'catalogue/fetchOne',
  async (id: string) => {
    const response = await fetchCatalogue(id)
    return response
  }
)

export const createCatalogueAsync = createAsyncThunk(
  'catalogue/add',
  async (data: { name: string; url: string }) => {
    const response = await addCatalogue(data.name, data.url)
    // The value we return becomes the `fulfilled` action payload
    return response
  }
)

export const catalogueSlice = createSlice({
  name: 'catalogue',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    clearCatalogueFlag: (state) => {
      state.status = ThunkStatus.Idle
    },
    clearCatalogueData: (state) => {
      state.catalogues = []
      state.status = ThunkStatus.Idle
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchCataloguesAsync.pending, (state) => {
        state.status = ThunkStatus.Loading
      })
      .addCase(fetchCataloguesAsync.fulfilled, (state, action) => {
        state.status = ThunkStatus.Success
        state.catalogues = action.payload
        state.error = undefined
      })
      .addCase(fetchCataloguesAsync.rejected, (state, action) => {
        state.status = ThunkStatus.Failed
        state.error = action.error.message
      })
      .addCase(fetchCatalogueAsync.pending, (state) => {
        state.status = ThunkStatus.Loading
      })
      .addCase(fetchCatalogueAsync.fulfilled, (state, action) => {
        state.status = ThunkStatus.Success
        state.catalogue = action.payload
        state.error = undefined
      })
      .addCase(fetchCatalogueAsync.rejected, (state, action) => {
        state.status = ThunkStatus.Failed
        state.error = action.error.message
      })
      .addCase(createCatalogueAsync.pending, (state) => {
        state.status = ThunkStatus.Loading
      })
      .addCase(createCatalogueAsync.fulfilled, (state, action) => {
        state.status = ThunkStatus.Success
        state.catalogue = action.payload
      })
      .addCase(createCatalogueAsync.rejected, (state, action) => {
        state.status = ThunkStatus.Failed
        state.error = action.error.message
      })
  },
})

export const { clearCatalogueData, clearCatalogueFlag } = catalogueSlice.actions

export default catalogueSlice.reducer
