import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'

import { fetchProduct, fetchProducts } from '../productAPI'
import { ProductDto } from '../productDtos'
import { ThunkStatus } from '../../ThunkStatus'

export interface ProductState {
  product?: ProductDto
  products: ProductDto[]
  status: ThunkStatus
  error?: string
}

const initialState: ProductState = {
  products: [],
  status: ThunkStatus.Idle,
}

export const fetchAsync = createAsyncThunk('product/fetch', async () => {
  const response = await fetchProducts()
  // The value we return becomes the `fulfilled` action payload
  return response
})

export const fetchOneAsync = createAsyncThunk(
  'product/fetchOne',
  async (id: string) => {
    const response = await fetchProduct(id)
    // The value we return becomes the `fulfilled` action payload
    return response
  }
)

export const productsSlice = createSlice({
  name: 'counter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    clearData: (state) => {
      state.products = []
      state.status = ThunkStatus.Idle
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAsync.pending, (state) => {
        state.status = ThunkStatus.Loading
      })
      .addCase(fetchAsync.fulfilled, (state, action) => {
        state.status = ThunkStatus.Success
        state.products = action.payload
      })
      .addCase(fetchAsync.rejected, (state, action) => {
        state.status = ThunkStatus.Failed
        state.error = action.error.message
      })
      .addCase(fetchOneAsync.pending, (state) => {
        state.status = ThunkStatus.Loading
      })
      .addCase(fetchOneAsync.fulfilled, (state, action) => {
        state.status = ThunkStatus.Success
        state.product = action.payload
      })
      .addCase(fetchOneAsync.rejected, (state, action) => {
        state.status = ThunkStatus.Failed
        state.error = action.error.message
      })
  },
})

export const { clearData } = productsSlice.actions

export default productsSlice.reducer
