import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'

import { fetchCatalogue } from '../catalogueAPI'
import { CatalogueDto } from '../catalogueDtos'
import { ThunkStatus } from '../../ThunkStatus'

export interface CatalogueState {
  catalogue?: CatalogueDto
  status: ThunkStatus
  error?: string
}

const initialState: CatalogueState = {
  catalogue: undefined,
  status: ThunkStatus.Idle,
}

export const fetchOneAsync = createAsyncThunk(
  'catalogue/fetchOne',
  async (id: string) => {
    const response = await fetchCatalogue(id)
    return response
  }
)

export const catalogueSlice = createSlice({
  name: 'catalogue',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    clearData: (state) => {
      state.catalogue = undefined
      state.status = ThunkStatus.Idle
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchOneAsync.pending, (state) => {
        state.status = ThunkStatus.Loading
      })
      .addCase(fetchOneAsync.fulfilled, (state, action) => {
        state.status = ThunkStatus.Success
        state.catalogue = action.payload
        state.error = undefined
      })
      .addCase(fetchOneAsync.rejected, (state, action) => {
        state.status = ThunkStatus.Failed
        state.error = action.error.message
      })
  },
})

export const { clearData } = catalogueSlice.actions

export default catalogueSlice.reducer
